language: ruby

rvm:
  - 2.4.0

env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database tuto_test' -U postgres
